export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGOUT_USER = "LOGOUT_USER";

export const FETCH_PLACES_SUCCESS = "FETCH_PLACES_SUCCESS";
export const FETCH_PLACE_SUCCESS = "FETCH_PLACE_SUCCESS";
export const DELETE_PLACE_SUCCESS = "DELETE_PLACE_SUCCESS";
export const CREATE_PLACE_SUCCESS = "CREATE_PLACE_SUCCESS";

export const FETCH_IMAGES_OF_PLACES_SUCCESS = "FETCH_IMAGES_OF_PLACES_SUCCESS"
export const FETCH_REVIEWS_OF_PLACES_SUCCESS = "FETCH_REVIEWS_OF_PLACES_SUCCESS"
